// Generated by https://quicktype.io

export interface DashboardSummaryResponse {
    numberOfOrders:         number;
    paidOrders:             number;
    notPaidOrders:          number;
    numberOfClients:        number;
    numberOfProducts:       number;
    numberWidthNoInventory: number;
    lowInventory:           number;
}
